name: argus
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - conda-forge::python=3.10
  - pytorch::pytorch=2.0
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  # - nvidia::cudatoolkit=11.8
  - conda-forge::pandas=1.5.3
  - conda-forge::black
  - conda-forge::pylint
  - conda-forge::pytest-cov
  - conda-forge::pyproj
  - conda-forge::matplotlib=3.7.1
  - conda-forge::tensorboard=2.13.0
  - conda-forge::jupyterlab
  - conda-forge::simplekml=1.3.6
  - conda-forge::pyqt
  - conda-forge::scikit-learn
  - pip:
    - sahi
    - openpyxl
    - opencv-python-headless
