name: argus
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - conda-forge::python=3.10.11
  - pytorch::pytorch=2
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.15.2
  - conda-forge::pandas=1.5.3
  - conda-forge::pyqt=5.15.7
  - pip
  - pip:
    - opencv-python-headless=4.8.1.78
    - sahi=0.11.14
    - openpyxl=3.1.2
